// src/utils/nifty100.js
export const NIFTY_50 = [
  { symbol: "ACC", name: "ACC Ltd." },
  { symbol: "ADANIENT", name: "Adani Enterprises Ltd." },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ Ltd." },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Ltd." },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise Ltd." },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Ltd." },
  { symbol: "ASIANPAINT", name: "Asian Paints Ltd." },
  { symbol: "AXISBANK", name: "Axis Bank Ltd." },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Ltd." },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Ltd." },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Ltd." },
  { symbol: "BPCL", name: "Bharat Petroleum Corp Ltd." },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Ltd." },
  { symbol: "BRITANNIA", name: "Britannia Industries Ltd." },
  { symbol: "CIPLA", name: "Cipla Ltd." },
  { symbol: "COALINDIA", name: "Coal India Ltd." },
  { symbol: "DIVISLAB", name: "Divi's Laboratories Ltd." },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories Ltd." },
  { symbol: "EICHERMOT", name: "Eicher Motors Ltd." },
  { symbol: "GAIL", name: "GAIL (India) Ltd." },
  { symbol: "GRASIM", name: "Grasim Industries Ltd." },
  { symbol: "HCLTECH", name: "HCL Technologies Ltd." },
  { symbol: "HDFCBANK", name: "HDFC Bank Ltd." },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance Co. Ltd." },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Ltd." },
  { symbol: "HINDALCO", name: "Hindalco Industries Ltd." },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Ltd." },
  { symbol: "ICICIBANK", name: "ICICI Bank Ltd." },
  { symbol: "ITC", name: "ITC Ltd." },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Ltd." },
  { symbol: "INFY", name: "Infosys Ltd." },
  { symbol: "JSWSTEEL", name: "JSW Steel Ltd." },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank Ltd." },
  { symbol: "LT", name: "Larsen & Toubro Ltd." },
  { symbol: "M&M", name: "Mahindra & Mahindra Ltd." },
  { symbol: "MARUTI", name: "Maruti Suzuki India Ltd." },
  { symbol: "NTPC", name: "NTPC Ltd." },
  { symbol: "NESTLEIND", name: "Nestle India Ltd." },
  { symbol: "ONGC", name: "Oil & Natural Gas Corporation Ltd." },
  { symbol: "POWERGRID", name: "Power Grid Corp. of India Ltd." },
  { symbol: "RELIANCE", name: "Reliance Industries Ltd." },
  { symbol: "SBILIFE", name: "SBI Life Insurance Co. Ltd." },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries Ltd." },
  { symbol: "TCS", name: "Tata Consultancy Services Ltd." },
  { symbol: "TATACONSUM", name: "Tata Consumer Products Ltd." },
  { symbol: "TATAMOTORS", name: "Tata Motors Ltd." },
  { symbol: "TATASTEEL", name: "Tata Steel Ltd." },
  { symbol: "TECHM", name: "Tech Mahindra Ltd." },
  { symbol: "TITAN", name: "Titan Company Ltd." },
  { symbol: "UPL", name: "UPL Ltd." },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Ltd." },
  { symbol: "WIPRO", name: "Wipro Ltd." },
  { symbol: "ADANIGREEN", name: "Adani Green Energy Ltd." },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Ltd." },
  { symbol: "BOSCHLTD", name: "Bosch Ltd." },
  { symbol: "CESC", name: "CESC Ltd." },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment & Finance Co. Ltd." },
  { symbol: "DABUR", name: "Dabur India Ltd." },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals Ltd." },
  { symbol: "HAVELLS", name: "Havells India Ltd." },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum Corporation Ltd." },
  { symbol: "HDFC", name: "Housing Development Finance Corp Ltd." },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance Co. Ltd." },
  { symbol: "IOC", name: "Indian Oil Corporation Ltd." },
  { symbol: "LTI", name: "L&T Infotech Ltd." },
  { symbol: "MINDTREE", name: "Mindtree Ltd." },
  { symbol: "MRF", name: "MRF Ltd." },
  { symbol: "NTPC", name: "NTPC Ltd." },
  { symbol: "ONGC", name: "ONGC Ltd." },
  { symbol: "PIIND", name: "PI Industries Ltd." },
  { symbol: "SBICARD", name: "SBI Cards & Payment Services Ltd." },
  { symbol: "SIEMENS", name: "Siemens Ltd." },
  { symbol: "SRF", name: "SRF Ltd." },
  { symbol: "TATACHEM", name: "Tata Chemicals Ltd." },
  { symbol: "TRENT", name: "Trent Ltd." },
  { symbol: "UPL", name: "UPL Ltd." },
  { symbol: "VEDL", name: "Vedanta Ltd." },
  { symbol: "ZEEL", name: "Zee Entertainment Enterprises Ltd." }
];
